import calendar
from tkinter import *
def showCalender(): #to display the 2nd window ( calender )
    gui = Tk()
    gui.config(background='white')
    gui.title("CALENDER")
    gui.geometry("550x600")
    year = int(year_field.get())
    gui_content= calendar.calendar(year)
    calYear = Label(gui, text= gui_content, font= "Consolas 10 bold")
    calYear.grid(row=5, column=1,padx=20)
    gui.mainloop()
if __name__=='__main__': #for the first window to ask the year
    new = Tk()
    new.config(background='white')
    new.title("Calender")
    new.geometry("250x150")
    cal = Label(new, text="Calender",bg='white',font=("times", 28, "bold"))
    year = Label(new, text="Enter year", bg='cyan')
    year_field=Entry(new)
    button = Button(new, text='Show Calender',fg='Black',bg='magenta',command=showCalender)
    cal.grid(row=1, column=1)
    year.grid(row=2, column=1)
    year_field.grid(row=3, column=1)
    button.grid(row=4, column=1)
    new.mainloop()